version: '3'

services:
  proxy:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/var/www/static
      - ./media:/var/www/media
    links:
        - web

  web:
    environment:
      - PYTHONUNBUFFERED=0
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./media:/code/media/
    ports:
      - "8000:8000"


  redis:
    image: redis
    ports:
      - '127.0.0.1:6379:6379'

  worker:
    build: .
    command: celery -A pdf_generator worker -l info -B -E
    volumes:
      - .:/code
    depends_on:
      - redis
